### ISSUE TITLE
About - link and page

### ISSUE THREAD

**Issue by michaelboer** [whatisleantv/whatisleantv.github.io#5]
Probably would be good to have an link on the main page for "about" that would explain what the website is about.....and a supporting page (or maybe it is just hover text)..... ?????  My 2 cents anyway.   :  )

**Comment by pancaek** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/20342389/20333375/efc79932-ab66-11e6-9687-8efe24d3f360.jpg)

**What do you think?**

**Comment by pancaek** [comment]
fixed with e98a8c105bf90929817e313ab230593b3396fa06
